settings:
  HA_URL: "https://<your-homeassistant-url>"
  RESPONSE_DIR: "/config/custom_components/openai_vision/responses"
  MEDIA_DIR: "/config/custom_components/openai_vision/responses"
  HASS_TOKEN: "<long-lived-hass-token>"
  OPENAI_API_KEY: "openai-api-key>"
  MODEL_CHOICES:
    - gpt-3.5-turbo
    - gpt-4
    - gpt-4o
    - gpt4-turbo
    - gpt-3.5-turbo-16k
